name: remote update

on: push
jobs:
  build:
    name: Build
    # Specify on which operating system we want this workflow to run
    runs-on: ubuntu-20.04
    # The steps that will be excuted
    steps:
      - name: Configure SSH
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          SSH_KEY: ${{ secrets.SSH_PRIVATE_SECRET_KEY }}
        run: |
          mkdir -p ~/.ssh/
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
          echo "$SSH_KEY" > ~/.ssh/github_actions
          chmod 600 ~/.ssh/github_actions
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add ~/.ssh/github_actions

      - name: Build and deploy
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run:
          #ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} bash scriptsample.sh
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }}
          && git checkout ${{ secrets.MAIN_BRANCH }}
          && git pull
          && exit"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show workspace
        run: |
          cd $GITHUB_WORKSPACE
          pwd
          dir
          ls -la

#  - name: connect and pull
#       run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull && exit"
#     - name: cleanup
#       run: rm -rf ~/.ssh
